#!/bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "This script uses functionality which requires root privileges"
    exit 1
fi

EBT="/sbin/ebtables"

$EBT -F
$EBT -X
$EBT -t filter -F
$EBT -t filter -X
$EBT -t nat -F
$EBT -t nat -X
$EBT -t broute -F
$EBT -t broute -X
